name: C++ CI

on:
  pull_request:        # Run on every PR update
  push:                # Also run on pushes to default branch (optional)
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ---- System dependencies -------------------------------------------------
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential ninja-build cmake pkg-config \
          libglfw3-dev libglew-dev libassimp-dev libglm-dev

    # ---- Configure & build ----------------------------------------------------
    - name: Configure (CMake)
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

    # ---- Run tests ------------------------------------------------------------
    - name: Run unit tests
      run: ctest --test-dir build --output-on-failure --verbose