name: C++ CI (Windows)

on:
  pull_request:           # every PR
  push:                   # optional – keep if you also want pushes to default branch checked
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest     # ← only Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # (Optional) Ninja gives faster multithreaded MSVC builds
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3    # small, cached action

    # ----- Configure & build -------------------------------------------------
    - name: Configure (CMake)
      run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

    # ----- Run Google-Tests ---------------------------------------------------
    - name: Run unit tests
      run: ctest --test-dir build --output-on-failure --verbose