name: C++ CI (Windows-MSVC)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Ensure MSVC toolchain is the one CMake sees
    - name: Set up MSVC env vars
      uses: ilammy/msvc-dev-cmd@v1        # sets PATH, CC, CXX → cl.exe

    # Optional: Ninja (faster than MSBuild)
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    # ---------- Configure & build with MSVC ----------
    - name: Configure (CMake – Ninja + MSVC)
      run: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release
      env:
        CC: cl
        CXX: cl

    - name: Build
      run: cmake --build build --parallel

    # ---------- Run unit tests ----------
    - name: Run tests
      run: ctest --test-dir build --output-on-failure --verbose